version: '3.8'

services:
  backend:
    image: sebast25/gestion-prestamos-backend:latest
    ports:
      - "8080:8080" # Mapea el puerto 8080 del contenedor al 8080 de la máquina host
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=sebastian
      - MAIL_USERNAME=cristhophervillamarin7@gmail.com
      - MAIL_PASSWORD=ayvq peua syeq aesn
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=sebastian
      - MYSQL_DATABASE=gestion_prestamos
    ports:
      - "3306:3306" # Opcional, para acceso externo si lo necesitas
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    image: sebast25/gestion-prestamos-frontend:latest
    ports:
      - "80:80" # Mapea el puerto 80 del contenedor al 80 de la máquina host
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: